### ISSUE TITLE
Project goal

### ISSUE THREAD

**Issue by eesaber** [eesaber/gcxWeb#1]
## Todos
- [ ] C++ account server based on [gRPC](https://github.com/grpc/grpc)
- [ ] web server by Go
  - [ ] survey Go Web API framework. 
- [ ] DB access by Go
- [ ] web server communicate with C++ account server by gRPC

**Comment by eesaber** [comment]
### Go Web API framework
1. [Gin](https://github.com/gin-gonic/gin)
